Ti.include('spec/spec_helper.js')
Ti.include('app.js')

Ti.include('spec/parse/parsejs_objects_spec.js')
Ti.include('spec/parse/parsejs_queries_spec.js')
Ti.include('spec/parse/parsejs_promises_spec.js')
Ti.include('spec/parse/parsejs_collections_spec.js')
Ti.include('spec/parse/parsejs_files_spec.js')
Ti.include('spec/parse/parsejs_analytics_spec.js')
Ti.include('spec/parse/parsejs_users_spec.js')
Ti.include('spec/parse/parsejs_roles_spec.js')
Ti.include('spec/parse/parsejs_facebook_specs.js')
Ti.include('spec/parse/parsejs_cloudfunctions_spec.js')
Ti.include('spec/parse/parsejs_geopoints_spec.js')
Ti.include('spec/parse/parsejs_push_specs.js')
